# Generated by Django 5.1.1 on 2024-10-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('primary_bank', models.CharField(max_length=255)),
                ('investment_accounts', models.TextField()),
                ('retirement_accounts', models.TextField()),
                ('investment_goals', models.TextField()),
                ('debt_types', models.TextField()),
                ('debt_amounts', models.TextField()),
                ('interest_rates', models.TextField()),
                ('debt_repayment_plans', models.TextField()),
                ('income_sources', models.TextField()),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_categories', models.TextField()),
                ('expense_amounts', models.TextField()),
                ('insurance_types', models.TextField()),
                ('insurance_coverage', models.TextField()),
                ('insurance_premiums', models.TextField()),
                ('short_term_goals', models.TextField()),
                ('long_term_goals', models.TextField()),
            ],
        ),
    ]
